image: debrum/ubuntu-jdk-mvn

stages:
  - test
  - build
  - build-docker
  - push-docker
  - deploy

unit-test-job:
  stage: test
  script:
    - mvn test

build-mvn-job:
  stage: build
  script:
    - mvn clean package -Dmaven.test.skip

build-docker-job:
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_DOCKER_USER -p $CI_DOCKER_PASSWORD

  stage: build-docker
  script:
    - docker build -t $URL_IMG_CONSUMER_DOCKER -f Dockerfile .

push-docker-job:
  stage: build-docker
  script:
    - docker push $URL_IMG_CONSUMER_DOCKER

deploy-k8s-job:
  stage: deploy-stage
  script:
    - echo "Deploying application..."
    - cat <<EOF > key.pem
      $PRIVATE_KEY
      EOF
    - chmod 400 key.pem
    # Entrar no aws
    - ssh -i key.pem ubuntu@$CLUSTER-DEV
    - kubectl create namespace $namespace-g3 # acho que não é legal ter isso aqui e sim rodar apenas uma vez na máquina
    - kubectl apply -f .k8s/deployments/consumer-dp.yaml
    # agora tem que rodar os arquivos do K8s
