image: debrum/ubuntu-jdk-mvn

stages:
  - test
  - build
  - build-docker
  - push-docker
  - deploy

unit-test-job:
  stage: test
  script:
    - mvn test

build-mvn-job:
  stage: build
  script:
    - mvn clean package -Dmaven.test.skip

build-docker-job:
  image: docker:latest
  services:
    - docker:18.09.7-dind
  before_script:
    - docker login -u ${CI_DOCKER_USER} -p ${CI_DOCKER_PASSWORD}

  stage: build-docker
  script:
    - docker build -t ${URL_IMG_CONSUMER_DOCKER} -f Dockerfile .
    - docker push ${URL_IMG_CONSUMER_DOCKER}

config-k8s-job:
  stage: deploy-stage
  script:
    - echo "Deploying application..."
    - echo "  KAFKA_HOST: ${kafka_host}" >> K8s/services/configmap.yml
    # - echo "  KAFKA_TOPIC: $kafka_topic" >> K8s/services/configmap.yml
    # - cat <<'EOF' >> K8s/services/configmap.yml
    #   "  KAFKA_HOST: $kafka_host"

deploy-k8s-job:
  stage: deploy-stage
  image: didox/ubuntu-ansible
  script:
    - echo "Deploying application..."
    - cat <<EOF > key.pem
      ${PRIVATE_KEY}
      EOF
    - chmod 400 key.pem
    - ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts prov.yml -u ubuntu --private-key key.pem
