apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
    id: "0"
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka-port
      protocol: TCP
  type: LoadBalancer
