apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeper-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zookeper-1
  template:
    metadata:
      labels:
        app: zookeper-1
    spec:
      containers:
        - name: zoo1
          image: zookeeper
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zoo1
